spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
  cache:
    jcache:
      config: ehcache.xml
  jpa:
    properties:
      hibernate:
        connection:
          charset: UTF-8
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor